---
Line: /$ANY*$EOL/
BlankLine: /$WS*$EOL/

# Module parsing grammar
Module:
- DocComment
- Comment*
- IncludeCDent
- Comment*
- Class
- (Class|Comment)*
- Ending
- Comments*

DocComment:
- DocCommentBegin
- DocCommentLine
- _:
  - DocCommentEnd!
  - DocCommentLine
  x: '*'
- DocCommentEnd

Comment: (LineComment|BlankLine)

Ending: //

LineComment: /$line_comment_start($Line)/
