---
# Module parsing grammar
Module:
- ModuleStart
- DocComment?
- Comment*
- IncludeCDent?
- Comment*
- Class
- (Class|Comment)*
- ModuleEnd
- Comment*

DocComment:
- DocCommentBegin
- _:
  - DocCommentEnd!
  - DocCommentLine
  x: '*'
- DocCommentEnd

Class:
- ClassStart
- ClassBody
- ClassEnd

ClassBody:
- indent
- Comment*
- Method
- (Method|Comment)*
- undent

Method:
- MethodStart
- MethodBody
- MethodEnd

MethodBody:
- indent
- Statement
- (Statement|Comment)*
- undent

Statement: (PrintLn|Comment)

Comment: (LineComment|BlankLine)

LineComment: /$line_comment_start($Line)/

Line: /$ANY*$EOL/
BlankLine: /$WS*$EOL/

ModuleStart: //
ModuleEnd: //

Id: /$WC+/
